os: Visual Studio 2017

environment:
  matrix:
    - SCALAR: 32bit
      RECOVERY: yes
    - SCALAR: 32bit
      FIELD: 32bit
      ECDH: yes
      EXPERIMENTAL: yes
    - SCALAR: 64bit
    - FIELD: 64bit
      RECOVERY: yes
    - FIELD: 64bit
      ENDOMORPHISM: yes
    - FIELD: 64bit
      ENDOMORPHISM: yes
      ECDH: yes
      EXPERIMENTAL: yes
    - FIELD: 64bit
      ASM: x86_64
    - FIELD: 64bit
      ENDOMORPHISM: yes
      ASM: x86_64
    - FIELD: 32bit
      ENDOMORPHISM: yes
    - BIGNUM: no
    - BIGNUM: no
      ENDOMORPHISM: yes
      RECOVERY: yes
      EXPERIMENTAL: yes
    - BIGNUM: no
      STATICPRECOMPUTATION: no
    - BUILD: distcheck
      CTIMETEST:
      BENCH:
    - EXTRAFLAGS: CPPFLAGS=-DDETERMINISTIC
    - EXTRAFLAGS: CFLAGS=-O0
    - ECMULTGENPRECISION: 2
    - ECMULTGENPRECISION: 8

install:
  - echo %SCALAR%
  # - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  # - rustup-init -yv --default-toolchain %channel% --default-host %target%
  # - cmd: |
  #     choco install gtools
  #     refreshenv
  #     pathed /user /add "%USERPROFILE%\.cargo\bin"
  #     if defined MSYS_BITS pathed /user /add "C:\msys64\mingw%MSYS_BITS%\bin"
  #     if defined MSYS_BITS pathed /user /add "C:\mingw%MSYS_BITS%\bin"
  #     refreshenv
  # - rustc -vV
  # - cargo -vV

build: false

# test_script:
#   - cargo build --verbose --no-default-features
#   - cargo build --verbose --no-default-features --features: "serde"
#   - cargo build --verbose --no-default-features --features: "lowmemory"
#   - cargo build --verbose --no-default-features --features: "rand"
#   - cargo build --verbose --no-default-features --features: "rand serde recovery endomorphism"
#   - cargo build --verbose --no-default-features --features: "fuzztarget recovery"
#   - cargo build --verbose --features: fuzztarget
#   - cargo build --verbose --features: rand
#   - cargo test --verbose --features: rand
#   - cargo test --verbose --features: "rand serde"
#   - cargo test --verbose --features: "rand serde recovery endomorphism"
#   - cargo build --verbose
#   - cargo test --verbose
#   - cargo build --verbose --release
#   - cargo test --verbose --release
#   - if "%channel%": : "nightly" (cargo test --benches --features: unstable)
#   - if "%channel%": : "stable" (
#     git clone https://github.com/emscripten-core/emsdk.git && cd emsdk && emsdk install latest && emsdk activate latest --global && emsdk_env.bat && cd .. &&
#     set "CARGO_TARGET_DIR: cargo_web" &&
#     cargo install --force --verbose cargo-web &&
#     set "CARGO_TARGET_DIR: " &&
#     cargo web build --verbose --target: asmjs-unknown-emscripten &&
#     cargo web test --verbose --target: asmjs-unknown-emscripten --nodejs)

# cache:
#   - 'C:\Users\appveyor\.cargo'
#   - 'C:\Users\appveyor\.rustup'
#   - 'target'
#   - 'cargo_web'

